services:
  next:
    container_name: next
    build:
      context: .
      dockerfile: dev.Dockerfile

    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - fe_printit

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  fe_printit:
    external: true